POST http://localhost:8080/order/start
Content-Type: application/json

{
  "orderer": {
    "userId": 2,
    "name": "김갑돌"
  },
  "orderLines": [
    {
      "productId": 2,
      "optionId": 1,
      "price": 20000,
      "quantity": 10
    },
    {
      "productId": 3,
      "optionId": 1,
      "price": 40000,
      "quantity": 4
    }
  ],
  "shippingInfo": {
    "address": {
      "address1": "경기도 용인시",
      "address2": "901호",
      "zipCode": "54321"
    },
    "receiver": {
      "name": "김갑돌",
      "phoneNumber": "010-2222-1111"
    }
  }
}

###
POST http://localhost:8080/order/start
Content-Type: application/json

{
  "orderer": {
    "userId": 1,
    "name": "이석준"
  },
  "orderLines": [
    {
      "productId": 1,
      "optionId": 1,
      "price": 10000,
      "quantity": 10
    },
    {
      "productId": 2,
      "optionId": 1,
      "price": 20000,
      "quantity": 20
    }
  ],
  "shippingInfo": {
    "address": {
      "address1": "서울시 관악구",
      "address2": "806호",
      "zipCode": "12345"
    },
    "receiver": {
      "name": "이석준",
      "phoneNumber": "010-1111-1111"
    }
  }
}