version: "3.8"
services:
  db:
    image: mysql:8.0.29
    container_name: order_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "order_db"
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_USER: "order_user"
      MYSQL_PASSWORD: "1234"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci